language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
    - php: 7

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install --no-interaction

before_script:
  - sudo pip install codecov
  - chmod +x .ci/mysql_fixtures.sh && .ci/mysql_fixtures.sh

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover=coverage.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi

after_success:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then codecov ; fi

notifications:
  email:
    - gulturyan@gmail.com
